apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-harbor-vm-secret-deployment
  labels:
    app: nginx-harbor-vm-app-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-harbor-vm-app-4
  template:
    metadata:
      labels:
        app: nginx-harbor-vm-app-4
    spec:
      containers:
      - name: nginx-harbor-vm-app-4
        image: harbor-vm.haas-401.pez.vmware.com/private-prj/nginx:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
       - name: ns1-harbor-vm-pull-secret
