apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: ubuntu-401.haas-401.pez.vmware.com
    path: /mnt/sharedfolder/tanzu-hol/nfs
