apiVersion: v1
kind: Pod
metadata:
  name: jumpbox-ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "apt -y update; apt -y install openssh-client; while true; do sleep 30; done;" ]
