apiVersion: run.tanzu.vmware.com/v1alpha1               #TKG API endpoint
kind: TanzuKubernetesCluster                            #required parameter
metadata:
  name: tkc-cluster-1                                   #cluster name, user defined
  namespace: ns1                                        #supervisor namespace
spec:
  distribution:
    version: v1.17.11                                    #resolved kubernetes version
  topology:
    controlPlane:
      count: 1                                          #number of control plane nodes
      class: best-effort-medium                         #vmclass for control plane nodes
      storageClass: pacific-gold-storage-policy         #storageclass for control plane
    workers:
      count: 2                                          #number of worker nodes
      class: best-effort-medium                         #vmclass for worker nodes
      storageClass: pacific-gold-storage-policy         #storageclass for worker nodes
  settings:
    network:
      cni:         
        name: antrea
      pods: 
        cidrBlocks:
        - 192.168.0.0/16                       #Cannot overlap with Supervisor Cluster
      serviceDomain: cluster.local
      services:
        cidrBlocks:
        - 10.96.0.0/12                         #Cannot overlap with Supervisor Cluster
